config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes, only: [:new, :create, :show, :index, :edit, :update] do
    resources :doses, only: [:new, :create]
  end
    resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
  validates :description, presence: true
  validates :description, presence: true
  validates_uniqueness_of :recipe, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dose_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Recipe.find(params[:recipe_id])
    @recipe = Recipe.new
  end

  def create
    dose = Dose.new(dose_params)
    recipe = Recipe.find(params[:recipe_id])
    ingredient = Ingredient.find(params[:dose][:ingredient_id])
    dose.recipe = recipe
    dose.ingredient = ingredient
    dose.save!
    redirect_to recipe_path(recipe)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to recipe_path(@dose.recipe)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_action :set_recipe, only: [:show]

  def index
    @recipes = Recipe.all
  end

  def show
    set_recipe
    @dose = Dose.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    set_recipe
  end

  def update
    set_recipe
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require('recipe').permit(:name, :description, :photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cool Recipe Collection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar-lewagon" style="padding: 30px; border-bottom: 1px solid black">
      <h1> <%=link_to 'Cool Recipe Collection', recipes_path%></h1>
      <button type="button" class="btn-shadow"><%= link_to 'Create new Recipe', new_recipe_path %></button>

  </div>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/recipes/edit.html.erb
<div class="container">
  <div style="text-align: left">
    <h1>Edit Recipe</h1>
    <div style="width: 500px">
      <%= simple_form_for (@recipe) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :category, collection: ['savory', 'sweet']%>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Save changes", class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h5 style="text-align: center; margin-top:20px">All Recipes [<%=Recipe.count%>]</h5>

  <div class="cards-container d-flex justify-content-between flex-wrap" style="padding: 0 15px">
    <% @recipes.each do |recipe| %>
    <div class="row">
      <div class="col-12-lg" style="padding: 0 0">
        <div class="card">
        <%= cl_image_tag recipe.photo, height: 340, width: 270, crop: :fill, class: 'card-img-top' %>
        <div class="card-body">
          <!-- <a href="#" class="stretched-link">Go somewhere</a> -->
          <h5 class="card-text"><%= link_to recipe.name, recipe_path(recipe)%></h5>
        </div>
      </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div style="text-align: left">
    <h1>Create new Recipe</h1>
    <div style="width: 500px">
      <%= simple_form_for (@recipe) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :category, collection: ['savory', 'sweet']%>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "add recipe", class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">

 <div class="card bg-dark text-white">
  <%= cl_image_tag @recipe.photo, class: 'card-img img-cover'%>
  <div class="card-img-overlay">
    <h5 class="card-title"><%= @recipe.name %></h5>
  </div>
</div>

  <div class="content d-flex justify-content-between">

    <div class="recipe-info" style="text-align: left">
      <h3>Description:</h3>
      <%= @recipe.description %>
      <br>
      <button type="button" class="btn-shadow"></i> <%= link_to 'edit', edit_recipe_path %></button>


    </div>

    <div class="ingredients-and-form">
      <div class="ingredients" style="text-align: left; margin-bottom: 50px">
      <h3>Ingredient list:</h3>
        <% @recipe.doses.each do |dose| %>
          <ul>
            <li>
            <strong><%= dose.description %></strong>
            <%= dose.ingredient.name %>
            <%= dose.ingredient.name %>
            <%= link_to '[delete]', dose_path(dose),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
            </li>
          </ul>
        <% end %>
      </div>
      <div class="form-dose" style="text-align: left">
        <h3>Add a new ingredient</h3>
        <div style="width: 500px">
          <%= simple_form_for ([@recipe, @dose]) do |f| %>
           <%= f.input :ingredient_id, collection: Ingredient.all %>
           <%= f.input :description %>
            <%= f.submit "Add ingredient", class: "btn-shadow" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>